Assignment Week 1

Tämän harjoituksen tavoitteena on rakentaa yksinkertainen neuroverkko, joka tunnistaa lajin (Iris) neljän numeerisen piirteen perusteella.
* Verholehden pituus (Sepal Length)
* Verholehden leveys (Sepal Width)
* Terälehden pituus (Petal Length)
* Terälehden leveys (Petal Width)

Harjoituksessa käytän Keras-kirjastoa rakentaakseen mallin, joka luokittelee kukat kolmen eri lajiin.
* Iris-Setosa
* Iris-Versicolor
* Iris-Virginica

In [18]:
import pandas as pd
import numpy as np
from tensorflow.keras.utils import to_categorical
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam

url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
column_names = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'species']
df = pd.read_csv(url, names=column_names)

df.head()

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

Neuroverkkoa varten data on valmisteltava:
1. Alkuperäinen data on järjestetty lajeittain., Käytän df.sample(frac1), jotta opetus- ja validointidatassa on kaikkia lajeja sekaisin
2. Muutan lajinimet vektoreiksi. Esimerkiksi laji 0 muuttuu

In [19]:
df = df.sample(frac=1).reset_index(drop=True)

X = df.drop('species', axis=1).values
y_raw = df['species'].values

encoder = LabelEncoder()
y_int = encoder.fit_transform(y_raw)
y = to_categorical(y_int)

df.head()

   sepal_length  sepal_width  petal_length  petal_width          species
0           4.9          3.1           1.5          0.1      Iris-setosa
1           5.7          3.0           4.2          1.2  Iris-versicolor
2           6.7          3.1           5.6          2.4   Iris-virginica
3           6.7          3.1           4.4          1.4  Iris-versicolor
4           5.0          2.3           3.3          1.0  Iris-versicolor

Tehtäväannon mukaisesti rakennan mallin, jossa on:
* Yksi piilokerros
* Ulostulokerros

In [20]:
model = Sequential([
    Dense(8, activation='relu', input_shape=(4,)),
    Dense(3, activation='softmax')
])

opt = Adam(learning_rate=0.01)

model.compile(optimizer=opt,
              loss='categorical_crossentropy',
              metrics=['accuracy'])

/home/ilkka/anaconda3/envs/keras/lib/python3.11/site-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Käytän 'validation_split=0.2' mallin opetukseen, eli jätän 20% datasta mallin testamiseen. Tavoitteena on saavuttaa vähintään 95% tarkkuus.

In [23]:
history = model.fit(X, y,
                    epochs=50,
                    batch_size=5,
                    validation_split=0.2,)

Epoch 1/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9917 - loss: 0.0477 - val_accuracy: 0.9667 - val_loss: 0.1722
Epoch 2/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9833 - loss: 0.0462 - val_accuracy: 0.9667 - val_loss: 0.1713
Epoch 3/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9750 - loss: 0.0699 - val_accuracy: 0.9667 - val_loss: 0.1463
Epoch 4/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9917 - loss: 0.0414 - val_accuracy: 0.9333 - val_loss: 0.2010
Epoch 5/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9667 - loss: 0.0805 - val_accuracy: 0.9000 - val_loss: 0.2387
Epoch 6/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9833 - loss: 0.0779 - val_accuracy: 0.9333 - val_loss: 0.1259
Epoch 7/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9833 - loss: 0.0604 - val_accuracy: 0.9667 - val_loss: 0.1898
Epoch 8/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9833 - loss: 0.0432 - val_accuracy: 0.9667 - val_loss: 0.1765
Epoch 9/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9833 - loss: 0.0444 - val_accuracy: 0.9667 - val_loss: 0.1521
Epoch 10/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9833 - loss: 0.0553 - val_accuracy: 0.9667 - val_loss: 0.1527
Epoch 11/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9750 - loss: 0.0521 - val_accuracy: 0.9667 - val_loss: 0.1851
Epoch 12/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9750 - loss: 0.0466 - val_accuracy: 0.9667 - val_loss: 0.1706
Epoch 13/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9833 - loss: 0.0425 - val_accuracy: 0.9667 - val_loss: 0.1713
Epoch 14/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9833 - loss: 0.0437 - val_accuracy: 0.9667 - val_loss: 0.1353
Epoch 15/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9917 - loss: 0.0389 - val_accuracy: 0.9000 - val_loss: 0.2226
Epoch 16/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9833 - loss: 0.0504 - val_accuracy: 0.9667 - val_loss: 0.1327
Epoch 17/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9750 - loss: 0.0634 - val_accuracy: 0.9667 - val_loss: 0.1320
Epoch 18/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9750 - loss: 0.0653 - val_accuracy: 0.9000 - val_loss: 0.2279
Epoch 19/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9833 - loss: 0.0437 - val_accuracy: 0.9333 - val_loss: 0.1261
Epoch 20/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9750 - loss: 0.0557 - val_accuracy: 0.9333 - val_loss: 0.2114
Epoch 21/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9667 - loss: 0.0629 - val_accuracy: 0.9667 - val_loss: 0.1814
Epoch 22/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9417 - loss: 0.1529 - val_accuracy: 0.9333 - val_loss: 0.1274
Epoch 23/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9583 - loss: 0.1647 - val_accuracy: 0.9000 - val_loss: 0.3833
Epoch 24/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9833 - loss: 0.0639 - val_accuracy: 0.9667 - val_loss: 0.1706
Epoch 25/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9833 - loss: 0.0430 - val_accuracy: 0.9333 - val_loss: 0.1941
Epoch 26/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9583 - loss: 0.1005 - val_accuracy: 0.9000 - val_loss: 0.2346
Epoch 27/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9833 - loss: 0.0627 - val_accuracy: 0.9667 - val_loss: 0.1472
Epoch 28/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9917 - loss: 0.0367 - val_accuracy: 0.9333 - val_loss: 0.2163
Epoch 29/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9833 - loss: 0.0606 - val_accuracy: 0.9667 - val_loss: 0.1806
Epoch 30/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9833 - loss: 0.0447 - val_accuracy: 0.9667 - val_loss: 0.1807
Epoch 31/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9667 - loss: 0.0800 - val_accuracy: 0.9667 - val_loss: 0.1686
Epoch 32/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9833 - loss: 0.0393 - val_accuracy: 0.9333 - val_loss: 0.1889
Epoch 33/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9833 - loss: 0.0409 - val_accuracy: 0.9667 - val_loss: 0.1684
Epoch 34/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9833 - loss: 0.0477 - val_accuracy: 0.9667 - val_loss: 0.1775
Epoch 35/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9833 - loss: 0.0471 - val_accuracy: 0.9667 - val_loss: 0.1573
Epoch 36/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9750 - loss: 0.0535 - val_accuracy: 0.9333 - val_loss: 0.1941
Epoch 37/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9833 - loss: 0.0364 - val_accuracy: 0.9333 - val_loss: 0.1292
Epoch 38/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9667 - loss: 0.0571 - val_accuracy: 0.9667 - val_loss: 0.1764
Epoch 39/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9750 - loss: 0.0501 - val_accuracy: 0.9667 - val_loss: 0.1525
Epoch 40/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9750 - loss: 0.0450 - val_accuracy: 0.9667 - val_loss: 0.1841
Epoch 41/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9833 - loss: 0.0458 - val_accuracy: 0.9667 - val_loss: 0.1600
Epoch 42/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9750 - loss: 0.0596 - val_accuracy: 0.9667 - val_loss: 0.1582
Epoch 43/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9833 - loss: 0.0593 - val_accuracy: 0.9667 - val_loss: 0.1792
Epoch 44/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9750 - loss: 0.0493 - val_accuracy: 0.9333 - val_loss: 0.2043
Epoch 45/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9833 - loss: 0.0614 - val_accuracy: 0.9667 - val_loss: 0.1401
Epoch 46/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9833 - loss: 0.0608 - val_accuracy: 0.9333 - val_loss: 0.1287
Epoch 47/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9667 - loss: 0.0594 - val_accuracy: 0.9667 - val_loss: 0.1483
Epoch 48/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9833 - loss: 0.0377 - val_accuracy: 0.9333 - val_loss: 0.2113
Epoch 49/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9833 - loss: 0.0471 - val_accuracy: 0.9667 - val_loss: 0.1474
Epoch 50/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9833 - loss: 0.0422 - val_accuracy: 0.9000 - val_loss: 0.2503